name: Gallery Builder Pro

on:
  push:
    paths:
      - 'images/**'          # 當圖片有變動時觸發
      - 'generate_all_readmes.py' # 當腳本有變動時觸發
  workflow_dispatch:          # 允許你手動按按鈕執行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # 務必確認這行存在，Action 才能幫你寫入 README
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: List files for debugging
        run: ls -R            # 幫你檢查檔案清單

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Pillow
        run: pip install Pillow

      - name: Generate All Readmes
        run: python ./generate_all_readmes.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 關鍵修正：確保同時追蹤根目錄與子目錄的 README
          git add README.md "**/README.md"
          
          # 如果有自動生成的 .jpg/.png 縮圖也要追蹤的話（目前腳本是直接引用原始圖，故這行選配）
          # git add "**/thumbnails/**"
          
          git commit -m "docs: sync all galleries and update root navigation" || exit 0
          git push